version: '3.8'

services:
  neo4j_osamas:
    image: neo4j:latest
    ports:
      - "7473:7474"
      - "7685:7687"
    volumes:
      - ./data:/data
      - ./csv:/var/lib/neo4j/import
      - ./datasets:/var/lib/neo4j/import  # Mount local datasets folder to Neo4j import directory
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_security_allow__csv__import__from__file__urls=true
      - NEO4J_dbms_directories_import=/var/lib/neo4j/import
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
